### ISSUE TITLE
Change the default branch

### ISSUE THREAD

**Issue by escherstair** [toradex/device-trees#1]
This repo has the default branch set to [toradex_5.4-2.1.x-imx](https://github.com/toradex/device-trees).
But this seems tom be a stale branch.
From the last commits it seems that the default branch is [toradex_5.4.y](https://github.com/toradex/device-trees/tree/toradex_5.4.y).
If this is the case, canm you change the default branch to this one?

Thanks

**Comment by leonheldattoradex** [comment]
@leograba can you please change the branch?
@escherstair thanks for pointing it out!

**Comment by leograba** [comment]
There are currently two active branches: [toradex_5.4.y](https://github.com/toradex/device-trees/tree/toradex_5.4.y) and [toradex_5.4-2.3.x-imx](https://github.com/toradex/device-trees/tree/toradex_5.4-2.3.x-imx)

Both are valid and the main difference is that one refers to the upstream kernel whereas the other refers to the NXP downstream kernel.

I'd prefer to update the default branch to `toradex_5.4-2.3.x-imx` to keep consistency: the previous default branch was an NXP downstream kernel, and the new one will continue to be an NXP downstream kernel.

Please let me know if any concerns.
